name: Build Flet App

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: apk
            runner: ubuntu-latest

          - target: aab
            runner: ubuntu-latest

          - target: web
            runner: ubuntu-latest

          - target: linux
            runner: ubuntu-latest

          - target: windows
            runner: windows-latest

          - target: macos
            runner: macos-latest

          - target: ipa
            runner: macos-latest

          - target: ios-simulator
            runner: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build app
        id: build
        uses: ndonkoHenri/flet-build-action@main
        with:
          target: ${{ matrix.target }}
          runner-python-version: "3.12"
          bundled-python-version: "3.12"
          build-number: ${{ github.run_number }}
          archive-output: true

      - name: Upload build archive
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.archive-path }}
          archive: false
          if-no-files-found: error
          overwrite: false
